name: Compile LaTeX and Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on push of tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LaTeX
        run: sudo apt-get install texlive-full
  
      - name: Compile LaTeX document
        run: |
          xelatex -output-directory=latex.out OmniView.tex
          cd latex.out
          makeglossaries OmniView
          cd ..
          xelatex -output-directory=latex.out OmniView.tex
          mv latex.out/OmniView.pdf ./

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Compiled-PDF
          path: OmniView.pdf


      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: OmniView.pdf
            draft: false
            prerelease: false
            token: ${{ secrets.GITHUB_TOKEN }}